### PR TITLE
Fix for issue 15: Some example code does not work

### LINKED ISSUE #15: Some example code don't work
Sample code in [Post-sign-in Confirmation](https://w3c.github.io/webappsec-credential-management/#examples-post-signin) and [Change Password](https://w3c.github.io/webappsec-credential-management/#examples-change-password) doesn't work. It returns `Uncaught TypeError: Failed to construct 'PasswordCredential': 'id' must not be empty.` error.  
This is caused by `input` elements missing `name` attribute.

### PR DESCRIPTION
**Pull request by battre**
The PasswordCredential(form) constructor requires name attributes for the username/password fields. Fixes #15.

### CODE REVIEW

**Comment by battre** [comment]
@vabr-g , @mikewest Can you please review? Thanks.

**Comment by battre** [comment]
Nevermind... by replacing `id` with `name`, the `<label for=''...">` reference becomes incorrect. I'll update the CL.

**Comment by battre** [comment]
Fixed

**Comment by vabr-g** [comment]
The patch LGTM, it makes the examples consistent with the spec.
However, I wonder why the spec does not accept id in lieu of name (form-based autofill does).

**Pull request merged**
