### PR TITLE
create separate security and privacy considerations sections

### LINKED ISSUE #186: W3C policy requires Privacy Considerations and Security Considerations to be separate sections
I merged PR #181 to main yesterday 17-Jan-2022 0908h and expected the [Credman editors' draft](https://w3c.github.io/webappsec-credential-management/) to be subsequently updated. However, today, I noticed that the [Credman editors' draft](https://w3c.github.io/webappsec-credential-management/) **was not updated** (the present editor's draft was published on 6-Jan-2022)

 [Actions > Build, Validate, and Publish > Run w3c/spec-prod@v2 > Generate Static HTML log](https://github.com/w3c/webappsec-credential-management/runs/4843974681?check_suite_focus=true) indicates that the problem is:

> Generate Static HTML
  [INFO] Build bikeshed document "index.bs" (common)…
    $ bikeshed --die-on=warning spec "index.bs" "index.bs.built.html" 
      LINE 2052: **W3C policy requires Privacy Considerations and Security Considerations to be separate sections, but you appear to have them combined into one.**
       ✘  Did not generate, due to fatal errors
    Failed

thus it appears that we need to tease section [6. Security and Privacy Considerations](https://w3c.github.io/webappsec-credential-management/#security-and-privacy) into two separate sections in order to get our editors' draft to be published.

a question: 
I do not see "security" nor "privacy" mentioned in the [Process Document](https://www.w3.org/2021/Process-20211102/) --- where is this apparently new requirement stated?

@nsatragno @jyasskin @wseltzer

### PR DESCRIPTION
**Pull request by equalsJeffH**
This is a very quickly done separation of section [6. Security and Privacy Considerations](https://w3c.github.io/webappsec-credential-management/#security-and-privacy) into two separate "security cons" and "privacy cons" sections in order to get our editors' draft to be published.

upon a quick scan it seemed the last two subsections were the only privacy-oriented ones, so I carved them into the new "privacy cons" section.

This will need review and polishing no doubt, but hopefully will re-instate editors' draft auto-updating. 

fixes #186

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/pull/187.html" title="Last updated on Jan 19, 2022, 8:56 PM UTC (c04caaf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/187/2311d7b...c04caaf.html" title="Last updated on Jan 19, 2022, 8:56 PM UTC (c04caaf)">Diff</a>

### CODE REVIEW

**Review by jyasskin — APPROVED** [review]
I think _Timing Attacks_ is also a privacy consideration. Otherwise, LGTM. It seems fine to split these sections even if https://github.com/w3c/specberus/issues/1346 concludes that it's not actually required.

**Review by nsatragno — APPROVED** [review]
lgtm % Jeffrey's comment.

**Comment by equalsJeffH** [comment]
> I think Timing Attacks is also a privacy consideration.

LOL indeed it is, I guess I didn't actually read it in my rush the first time around :zany_face: 

fixed in c04caaf

**Comment by equalsJeffH** [comment]
This PR indeed fixed the [editors' draft](https://w3c.github.io/webappsec-credential-management/) spec publishing problem that instigated issue #186.

**Pull request merged**
