### PR TITLE
Request() needs new

### PR DESCRIPTION
**Pull request by tyoshino**

### CODE REVIEW

**Comment by vabr-g** [comment]
Thanks for the fix. It looks clearly like an improvement, I just never merged a pull request on GitHub before, and I don't understand the failing checks. So please bear with me as I ask @mikewest a couple of questions!

**Comment by mikewest** [comment]
@wseltzer: @tyoshino is a Google employee. Can we add him to whatever whitelist y'all use for IPR considerations?

**Comment by vabr-g** [comment]
Meanwhile, after talking to @mikewest, the failing IPR check does not block merging this request, because the proposed change does not make any normative change potentially covered by IPR-related agreements. I am going to (try to) merge the PR.

**Comment by tyoshino** [comment]
Thanks!

**Comment by wseltzer** [comment]
Marked as non-substantive for IPR from ash-nazg.

**Pull request merged**
