### PR TITLE
Use new mixin IDL syntax

### LINKED ISSUE #111: Update WebIDL definition(s) to use new mixin syntax
Hi all!

WebIDL recently introduced [dedicated syntax for mixins][0].

This syntax replaces the `[NoInterfaceObject]` extended attribute and `implements statement` which have been deprecated (except for a few [legacy uses cases][1] explicitely mentioned in the spec).

You can read more about it [here][2].

In most cases, the changes should be relatively straightforward. The now deprecated:

```webidl
interface Foo { };

[NoInterfaceObject]  // (Mostly) DEPRECATED
interface Bar { };
Foo implementes Bar; // DEPRECATED
```

should just be rewritten as:

```webidl
interface Foo { };

interface mixin Bar { };
Foo includes Bar;
```

Additonaly, a section on [when to use partials and mixins][3] has been added to the spec. It's short and might be worth a read.

It seems the following interfaces in this spec are impacted by this change:

- [ ] CredentialUserData

We're sorry for the inconvenience this causes, but our hope is that this ultimately makes things simpler and clearer for everybody.

As always, please feel free to reach out if you have any questions.

Thanks!

[0]: https://github.com/heycam/webidl/commit/45e8173d40ddff8dcf81697326e094bcf8b92920
[1]: https://heycam.github.io/webidl/#NoInterfaceObject
[2]: https://heycam.github.io/webidl/#idl-interface-mixins
[3]: https://heycam.github.io/webidl/#using-mixins-and-partials

***

*Tracked in: heycam/webidl#472* | *Original pull-request: heycam/webidl#433*

### PR DESCRIPTION
**Pull request by saschanaz**
Closes #111 

CC: @marcoscaceres

***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/webappsec-credential-management/pull/119.html" title="Last updated on May 21, 2018, 4:05 AM GMT (1537051)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-credential-management/119/ad41ec2...saschanaz:1537051.html" title="Last updated on May 21, 2018, 4:05 AM GMT (1537051)">Diff</a>

### CODE REVIEW

**Comment by saschanaz** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by saschanaz** [comment]
Hi @mikewest, it seems the page hasn't been rebuilt for a while. Should I open another PR for this?

**Comment by mikewest** [comment]
Rebuilt in https://github.com/w3c/webappsec-credential-management/commit/e62cb761e7e2602053ba79e1ed7745c15e409d5e. Thanks!

**Comment by saschanaz** [comment]
Thank you :+1:

**Pull request merged**
